services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&  python manage.py migrate &&  python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16.0-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - my_db:$PGDATA

volumes:
  my_db:
